# Generated by Django 2.1.5 on 2019-01-14 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='base_fee',
            field=models.IntegerField(verbose_name='基本料金'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='charge_fee',
            field=models.IntegerField(verbose_name='従量料金'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='subject',
            field=models.CharField(max_length=30, verbose_name='科目'),
        ),
    ]
