# Generated by Django 2.1.5 on 2019-01-14 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbms', '0002_auto_20190114_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='billing',
            field=models.IntegerField(verbose_name='請求料金'),
        ),
    ]
