# Generated by Django 2.1.5 on 2019-01-19 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbms', '0003_auto_20190114_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='time',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='受講時間'),
        ),
    ]
