# Generated by Django 2.1.5 on 2019-01-19 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbms', '0004_auto_20190119_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='billing',
        ),
    ]
